import { renderToStaticMarkup } from 'react-dom/server';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/** Turns Markdown into a clean, printable HTML document (used for PDF preview/download). */
export function markdownToDocumentHtml(title: string, markdown: string): string {
  const body = renderToStaticMarkup(<ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>);
  const safeTitle = title.replace(/[<>&"]/g, '');
  return `<!doctype html>
<html><head><meta charset="utf-8"/><title>${safeTitle}</title>
<style>
  @page { margin: 18mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Noto Sans Bengali', 'Segoe UI', system-ui, -apple-system, Arial, sans-serif; color:#1B1B2F; line-height:1.65; font-size:14px; margin:0; padding:32px 40px; }
  .brand { display:flex; align-items:center; gap:10px; border-bottom:2px solid #7C6CFF; padding-bottom:12px; margin-bottom:24px; }
  .logo { width:32px; height:32px; border-radius:10px; background:linear-gradient(135deg,#7C6CFF,#22C3E6); }
  .brand b { font-size:16px; } .brand span { color:#7A78A0; font-size:12px; display:block; }
  h1 { font-size:26px; margin:0 0 12px; } h2 { font-size:19px; margin:22px 0 8px; color:#5B4BDB; } h3 { font-size:15px; margin:16px 0 6px; }
  code { background:#F1EEFF; color:#5B4BDB; padding:1px 6px; border-radius:5px; font-family: ui-monospace, Menlo, Consolas, monospace; font-size:12.5px; }
  table { border-collapse:collapse; width:100%; margin:12px 0; } th,td { border:1px solid #E2DFF5; padding:8px 10px; text-align:left; font-size:13px; } th { background:#F1EEFF; }
  blockquote { border-left:4px solid #7C6CFF; margin:12px 0; padding:4px 14px; background:#FAF9FF; color:#4B4B63; }
  footer { margin-top:32px; padding-top:10px; border-top:1px solid #E2DFF5; color:#8C8AA8; font-size:11px; }
</style></head>
<body>
  <div class="brand"><div class="logo"></div><div><b>Pragati AI Teacher</b><span>CSE study notes</span></div></div>
  ${body}
  <footer>Generated by Pragati AI Teacher</footer>
</body></html>`;
}
